### ISSUE TITLE
LiDAR incoming frame too old, need to be drop!!!

### ISSUE THREAD

**Issue by sreejithsreeni** [KeepOnKeepOn/r3live#1]
I have an issue with Hesai Lidar and D435i, r3live mapping. When I launch the mapping file I got the following error. 
not ready for odometry
LiDAR incoming frame too old, need to be drop!!!

Please assist to solve the issue/

**Comment by sreesms** [comment]
This error is because of the mismatch of timestamp. Solved after fixing the timestamp of camera and Lidar.

**Comment by sreejithsreeni** [comment]
This error is because of the mismatch of timestamp. Solved after fixing the timestamp of camera and Lidar.
